// design/{tokens,strings} → output map { relativePath: content }.
// Pure: gen.mjs writes this map to disk, check.mjs compares it against disk (drift check).
import { readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

export const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");

const HEADER = "GENERATED by tools/design-gen from design/ — do not edit. Run `pnpm design:gen`.";

export const OUT = {
  css: "workbench/src/generated/tokens.css",
  ts: "workbench/src/generated/tokens.ts",
  stringsTs: "workbench/src/generated/strings.ts",
  swiftTokens: "swift/Packages/IthacaDesign/Sources/IthacaDesign/Generated/Tokens.swift",
  swiftStrings: "swift/Packages/IthacaDesign/Sources/IthacaDesign/Generated/Strings.swift",
  ktTokens: "kotlin/design/src/commonMain/kotlin/io/github/colosan/ithaca/design/generated/Tokens.kt",
  ktStrings: "kotlin/design/src/commonMain/kotlin/io/github/colosan/ithaca/design/generated/Strings.kt",
};

// ── Read ────────────────────────────────────────────────────────────────

const readJson = (rel) => JSON.parse(readFileSync(join(ROOT, rel), "utf8"));

export function loadDesign() {
  const tokens = {
    color: readJson("design/tokens/color.json"),
    typography: readJson("design/tokens/typography.json"),
    spacing: readJson("design/tokens/spacing.json"),
    sizing: readJson("design/tokens/sizing.json"),
    effects: readJson("design/tokens/effects.json"),
    layout: readJson("design/tokens/layout.json"),
  };
  const locales = ["ko", "en"];
  const strings = Object.fromEntries(locales.map((l) => [l, readJson(`design/strings/${l}.json`)]));
  return { tokens, locales, strings };
}

/** Ensure every locale has the same key set before generating; otherwise the Swift/Kotlin tables would have holes. */
function assertSameKeys({ locales, strings }) {
  const ref = Object.keys(strings[locales[0]]);
  for (const l of locales) {
    const missing = ref.filter((k) => !(k in strings[l]));
    const extra = Object.keys(strings[l]).filter((k) => !ref.includes(k));
    if (missing.length || extra.length)
      throw new Error(`design/strings/${l}.json 키 불일치 — 없음: [${missing.join(", ")}] · 남음: [${extra.join(", ")}]. pnpm design:check 로 확인`);
  }
}

// ── Names ───────────────────────────────────────────────────────────────

const parts = (name) => String(name).split(/[.\-_]/).filter(Boolean);
export const camel = (name) =>
  parts(name).map((p, i) => (i === 0 ? p[0].toLowerCase() + p.slice(1) : p[0].toUpperCase() + p.slice(1))).join("");
export const kebab = (name) =>
  parts(name).map((p) => p.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase()).join("-");
const upperSnake = (name) => kebab(name).replace(/-/g, "_").toUpperCase();
const scaleId = (key) => `s${key}`; // spacing "200" → s200 (Swift/Kotlin identifiers cannot start with a digit)

const hexBody = (hex) => {
  const h = hex.slice(1).toUpperCase();
  return h.length === 6 ? { rgb: h, a: "FF" } : { rgb: h.slice(0, 6), a: h.slice(6) };
};
const swiftRGBA = (hex) => { const { rgb, a } = hexBody(hex); return `0x${rgb}${a}`; };
const kotlinARGB = (hex) => { const { rgb, a } = hexBody(hex); return `0x${a}${rgb}L`; };

const num = (n) => (Number.isInteger(n) ? `${n}` : `${n}`);
const swiftDouble = (n) => (Number.isInteger(n) ? `${n}` : `${n}`);
const ktFloat = (n) => `${n}f`;

const swiftStr = (s) => `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
const ktStr = (s) => `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\$/g, "\\$")}"`;
const tsStr = (s) => JSON.stringify(s);

// ── CSS · TS (workbench) ───────────────────────────────────────────────

function buildCss({ tokens }) {
  const { color, typography, spacing, sizing, effects, layout } = tokens;
  const modeBlock = (mode) =>
    Object.entries(color.tokens).map(([k, v]) => `  --color-${kebab(k)}: ${v[mode]};`).join("\n");

  const fam = (f) => [`"${f.name}"`, ...f.fallback].join(", ");
  const lines = [];
  for (const [k, f] of Object.entries(typography.families)) lines.push(`  --font-${kebab(k)}: ${fam(f)};`);
  // Sizes are the default-text-size values; --text-scale mimics the OS text size setting (Dynamic Type, font scale).
  // Custom properties resolve var() where they are declared, so these live in their own block that is redeclared
  // on every themed element (each workbench frame) — a frame can then set its own --text-scale.
  const typeLines = [];
  for (const [k, s] of Object.entries(typography.styles)) {
    const p = `--type-${kebab(k)}`;
    lines.push(`  ${p}-family: var(--font-${kebab(s.family)});`, `  ${p}-tracking: ${s.tracking}em;`, `  ${p}-weight: ${s.weight};`);
    typeLines.push(
      `  ${p}-size: calc(${s.size}px * var(--text-scale, 1));`,
      `  ${p}-line-height: calc(${s.lineHeight}px * var(--text-scale, 1));`,
    );
  }
  for (const [k, v] of Object.entries(spacing.scale)) lines.push(`  --space-${k}: ${v}px;`);
  for (const [k, v] of Object.entries(sizing.sizes)) lines.push(`  --size-${kebab(k)}: ${v}px;`);
  for (const [k, v] of Object.entries(effects.radius)) lines.push(`  --radius-${kebab(k)}: ${v}px;`);
  for (const [k, v] of Object.entries(effects.shadow))
    lines.push(`  --shadow-${kebab(k)}: 0 ${v.y}px ${v.blur}px rgba(0, 0, 0, ${v.opacity});`);
  for (const [k, v] of Object.entries(effects.opacity)) lines.push(`  --opacity-${kebab(k)}: ${v};`);
  for (const [k, v] of Object.entries(effects.motion))
    lines.push(
      `  --motion-${kebab(k)}-duration: ${v.duration}ms;`,
      `  --motion-${kebab(k)}-easing: cubic-bezier(${v.easing.join(", ")});`,
    );
  for (const [k, v] of Object.entries(layout.panes)) lines.push(`  --pane-${kebab(k)}: ${v.default}px;`);
  lines.push(`  --editor-measure: ${layout.editor.measure}px;`);
  lines.push(`  --window-min-width: ${layout.window.minWidth}px;`, `  --window-min-height: ${layout.window.minHeight}px;`);
  for (const [k, v] of Object.entries(layout.editor.paddingX)) lines.push(`  --editor-padding-x-${k}: ${v}px;`);

  return [
    `/* ${HEADER} */`,
    ``,
    `:root,`,
    `[data-theme="light"] {`,
    modeBlock("light"),
    `}`,
    ``,
    `[data-theme="dark"] {`,
    modeBlock("dark"),
    `}`,
    ``,
    `:root,`,
    `[data-theme] {`,
    ...typeLines,
    `}`,
    ``,
    `:root {`,
    ...lines,
    `}`,
    ``,
  ].join("\n");
}

function buildTs({ tokens }) {
  const { color, typography, spacing, sizing, effects, layout } = tokens;
  const obj = (entries) => `{\n${entries.map(([k, v]) => `  ${k}: ${v},`).join("\n")}\n}`;

  const colorTs = obj(Object.keys(color.tokens).map((k) => [camel(k), tsStr(`var(--color-${kebab(k)})`)]));
  const typeTs = obj(
    Object.keys(typography.styles).map((k) => {
      const p = `--type-${kebab(k)}`;
      return [
        camel(k),
        `{ fontFamily: "var(${p}-family)", fontSize: "var(${p}-size)", lineHeight: "var(${p}-line-height)", letterSpacing: "var(${p}-tracking)", fontWeight: "var(${p}-weight)" }`,
      ];
    }),
  );
  const spaceTs = obj(Object.keys(spacing.scale).map((k) => [k, tsStr(`var(--space-${k})`)]));
  const sizeTs = obj(Object.keys(sizing.sizes).map((k) => [camel(k), tsStr(`var(--size-${kebab(k)})`)]));
  const radiusTs = obj(Object.keys(effects.radius).map((k) => [camel(k), tsStr(`var(--radius-${kebab(k)})`)]));
  const shadowTs = obj(Object.keys(effects.shadow).map((k) => [camel(k), tsStr(`var(--shadow-${kebab(k)})`)]));
  const opacityTs = obj(Object.keys(effects.opacity).map((k) => [camel(k), tsStr(`var(--opacity-${kebab(k)})`)]));
  const motionTs = obj(
    Object.keys(effects.motion).map((k) => [
      camel(k),
      `{ duration: "var(--motion-${kebab(k)}-duration)", easing: "var(--motion-${kebab(k)}-easing)" }`,
    ]),
  );
  const paneTs = obj(Object.keys(layout.panes).map((k) => [camel(k), tsStr(`var(--pane-${kebab(k)})`)]));
  const padTs = obj(Object.keys(layout.editor.paddingX).map((k) => [k, tsStr(`var(--editor-padding-x-${k})`)]));
  const classes = Object.entries(layout.sizeClasses);

  return [
    `// ${HEADER}`,
    `// Values are CSS variable references; colors follow the frame's data-theme.`,
    ``,
    `export const color = ${colorTs} as const;`,
    ``,
    `export const type = ${typeTs} as const;`,
    ``,
    `export const space = ${spaceTs} as const;`,
    ``,
    `export const size = ${sizeTs} as const;`,
    ``,
    `export const radius = ${radiusTs} as const;`,
    ``,
    `export const shadow = ${shadowTs} as const;`,
    ``,
    `export const opacity = ${opacityTs} as const;`,
    ``,
    `export const motion = ${motionTs} as const;`,
    ``,
    `export const pane = ${paneTs} as const;`,
    ``,
    `export const editor = { measure: "var(--editor-measure)", paddingX: ${padTs.replace(/\n/g, "\n  ")} } as const;`,
    ``,
    `/** Smallest desktop window (Mac, Windows). Raw numbers — for frame limits, not styles. */`,
    `export const windowMin = { width: ${layout.window.minWidth}, height: ${layout.window.minHeight} } as const;`,
    ``,
    `export type SizeClass = ${classes.map(([k]) => tsStr(k)).join(" | ")};`,
    ``,
    `/** Raw numbers from layout.json — for layout branching logic only (do not use as style values). */`,
    `export const sizeClasses: ReadonlyArray<{ name: SizeClass; min: number; max: number | null; referenceViewport: readonly [number, number]; panes: number }> = [`,
    ...classes.map(
      ([k, v]) =>
        `  { name: ${tsStr(k)}, min: ${v.min}, max: ${v.max === null ? "null" : v.max}, referenceViewport: [${v.referenceViewport.join(", ")}], panes: ${v.panes} },`,
    ),
    `];`,
    ``,
    `export function sizeClassFor(width: number): SizeClass {`,
    `  for (const c of sizeClasses) if (width >= c.min && (c.max === null || width <= c.max)) return c.name;`,
    `  return ${tsStr(classes[0][0])};`,
    `}`,
    ``,
  ].join("\n");
}

// ── Strings────────────────────────────────────────────────────────────

export const placeholders = (value) => {
  const texts = typeof value === "string" ? [value] : Object.values(value);
  const set = new Set();
  for (const t of texts) for (const m of t.matchAll(/\{(\w+)\}/g)) set.add(m[1]);
  return [...set].sort();
};

function buildStringsTs({ locales, strings }) {
  const keys = Object.keys(strings[locales[0]]);
  const table = Object.fromEntries(locales.map((l) => [l, strings[l]]));
  return [
    `// ${HEADER}`,
    ``,
    `export const locales = [${locales.map(tsStr).join(", ")}] as const;`,
    `export type Locale = (typeof locales)[number];`,
    ``,
    `export type StringKey =`,
    ...keys.map((k) => `  | ${tsStr(k)}`),
    `  ;`,
    ``,
    `type Value = string | { one: string; other: string };`,
    ``,
    `export const strings: Record<Locale, Record<StringKey, Value>> = ${JSON.stringify(table, null, 2)};`,
    ``,
    `/** Plurals: ko has none; en uses "one" when count === 1 (ADR-0005). Numeric params get locale digit grouping. */`,
    `export function format(locale: Locale, key: StringKey, params: Record<string, string | number> = {}): string {`,
    `  const v = strings[locale][key];`,
    `  const count = typeof params.count === "number" ? params.count : Number(params.count);`,
    `  let s = typeof v === "string" ? v : count === 1 ? v.one : v.other;`,
    `  for (const [k, p] of Object.entries(params))`,
    `    s = s.split("{" + k + "}").join(typeof p === "number" ? p.toLocaleString(locale) : p);`,
    `  return s;`,
    `}`,
    ``,
  ].join("\n");
}

function buildSwiftStrings({ locales, strings }) {
  const keys = Object.keys(strings[locales[0]]);
  const val = (v) =>
    typeof v === "string" ? `.text(${swiftStr(v)})` : `.plural(one: ${swiftStr(v.one)}, other: ${swiftStr(v.other)})`;
  return [
    `// ${HEADER}`,
    `// ADR-0005: read this table directly instead of OS resources so the language can switch in-app instantly.`,
    ``,
    `public enum L10nLocale: String, CaseIterable, Sendable {`,
    ...locales.map((l) => `    case ${l}`),
    `}`,
    ``,
    `public enum L10nKey: String, CaseIterable, Sendable {`,
    ...keys.map((k) => `    case ${camel(k)} = ${swiftStr(k)}`),
    `}`,
    ``,
    `enum L10nValue: Sendable {`,
    `    case text(String)`,
    `    case plural(one: String, other: String)`,
    `}`,
    ``,
    `public enum L10n {`,
    `    public static func string(_ key: L10nKey, locale: L10nLocale, _ args: [String: String] = [:], count: Int? = nil) -> String {`,
    `        guard let value = table[locale]?[key] else { return key.rawValue }`,
    `        var s: String`,
    `        switch value {`,
    `        case .text(let t): s = t`,
    `        case .plural(let one, let other): s = (count == 1) ? one : other`,
    `        }`,
    `        var all = args`,
    `        if let count, all["count"] == nil { all["count"] = String(count) }`,
    `        for (k, v) in all { s = s.replacingOccurrences(of: "{" + k + "}", with: v) }`,
    `        return s`,
    `    }`,
    ``,
    `    static let table: [L10nLocale: [L10nKey: L10nValue]] = [`,
    ...locales.flatMap((l) => [
      `        .${l}: [`,
      ...keys.map((k) => `            .${camel(k)}: ${val(strings[l][k])},`),
      `        ],`,
    ]),
    `    ]`,
    `}`,
    ``,
  ].join("\n");
}

function buildKtStrings({ locales, strings }) {
  const keys = Object.keys(strings[locales[0]]);
  const val = (v) =>
    typeof v === "string" ? `L10nValue.Text(${ktStr(v)})` : `L10nValue.Plural(one = ${ktStr(v.one)}, other = ${ktStr(v.other)})`;
  return [
    `// ${HEADER}`,
    `// ADR-0005: read this table directly instead of OS resources so the language can switch in-app instantly.`,
    `package io.github.colosan.ithaca.design.generated`,
    ``,
    `enum class L10nLocale { ${locales.join(", ")} }`,
    ``,
    `enum class L10nKey(val key: String) {`,
    ...keys.map((k) => `    ${upperSnake(k)}(${ktStr(k)}),`),
    `}`,
    ``,
    `sealed interface L10nValue {`,
    `    data class Text(val text: String) : L10nValue`,
    `    data class Plural(val one: String, val other: String) : L10nValue`,
    `}`,
    ``,
    `object L10n {`,
    `    fun string(key: L10nKey, locale: L10nLocale, args: Map<String, String> = emptyMap(), count: Int? = null): String {`,
    `        val value = table[locale]?.get(key) ?: return key.key`,
    `        var s = when (value) {`,
    `            is L10nValue.Text -> value.text`,
    `            is L10nValue.Plural -> if (count == 1) value.one else value.other`,
    `        }`,
    `        val all = if (count != null && "count" !in args) args + ("count" to count.toString()) else args`,
    `        for ((k, v) in all) s = s.replace("{" + k + "}", v)`,
    `        return s`,
    `    }`,
    ``,
    `    private val table: Map<L10nLocale, Map<L10nKey, L10nValue>> = mapOf(`,
    ...locales.flatMap((l) => [
      `        L10nLocale.${l} to mapOf(`,
      ...keys.map((k) => `            L10nKey.${upperSnake(k)} to ${val(strings[l][k])},`),
      `        ),`,
    ]),
    `    )`,
    `}`,
    ``,
  ].join("\n");
}

// ── Swift · Kotlin tokens───────────────────────────────────────────────

function buildSwiftTokens({ tokens }) {
  const { color, typography, spacing, sizing, effects, layout } = tokens;
  const classes = Object.entries(layout.sizeClasses);
  return [
    `// ${HEADER}`,
    ``,
    `/// A light/dark color pair. Values are 0xRRGGBBAA.`,
    `public struct ColorPair: Sendable, Equatable {`,
    `    public let light: UInt32`,
    `    public let dark: UInt32`,
    `}`,
    ``,
    `public struct TextStyleToken: Sendable, Equatable {`,
    `    public let family: String`,
    `    public let size: Double`,
    `    public let lineHeight: Double`,
    `    /// em`,
    `    public let tracking: Double`,
    `    public let weight: Int`,
    `}`,
    ``,
    `public struct ShadowToken: Sendable, Equatable {`,
    `    public let y: Double`,
    `    public let blur: Double`,
    `    public let opacity: Double`,
    `}`,
    ``,
    `public struct MotionToken: Sendable, Equatable {`,
    `    /// milliseconds`,
    `    public let duration: Double`,
    `    public let x1: Double, y1: Double, x2: Double, y2: Double`,
    `}`,
    ``,
    `public enum Tokens {`,
    `    public enum Color {`,
    ...Object.entries(color.tokens).map(
      ([k, v]) => `        public static let ${camel(k)} = ColorPair(light: ${swiftRGBA(v.light)}, dark: ${swiftRGBA(v.dark)})`,
    ),
    `    }`,
    ``,
    `    public enum Typography {`,
    `        public enum Family {`,
    ...Object.entries(typography.families).map(([k, f]) => `            public static let ${camel(k)} = ${swiftStr(f.name)}`),
    `        }`,
    ...Object.entries(typography.styles).map(
      ([k, s]) =>
        `        public static let ${camel(k)} = TextStyleToken(family: Family.${camel(s.family)}, size: ${swiftDouble(s.size)}, lineHeight: ${swiftDouble(s.lineHeight)}, tracking: ${swiftDouble(s.tracking)}, weight: ${s.weight})`,
    ),
    `    }`,
    ``,
    `    public enum Space {`,
    ...Object.entries(spacing.scale).map(([k, v]) => `        public static let ${scaleId(k)}: Double = ${num(v)}`),
    `    }`,
    ``,
    `    public enum Size {`,
    ...Object.entries(sizing.sizes).map(([k, v]) => `        public static let ${camel(k)}: Double = ${num(v)}`),
    `    }`,
    ``,
    `    public enum Radius {`,
    ...Object.entries(effects.radius).map(([k, v]) => `        public static let ${camel(k)}: Double = ${num(v)}`),
    `    }`,
    ``,
    `    public enum Shadow {`,
    ...Object.entries(effects.shadow).map(
      ([k, v]) => `        public static let ${camel(k)} = ShadowToken(y: ${num(v.y)}, blur: ${num(v.blur)}, opacity: ${num(v.opacity)})`,
    ),
    `    }`,
    ``,
    `    public enum Opacity {`,
    ...Object.entries(effects.opacity).map(([k, v]) => `        public static let ${camel(k)}: Double = ${num(v)}`),
    `    }`,
    ``,
    `    public enum Motion {`,
    ...Object.entries(effects.motion).map(
      ([k, v]) =>
        `        public static let ${camel(k)} = MotionToken(duration: ${num(v.duration)}, x1: ${v.easing[0]}, y1: ${v.easing[1]}, x2: ${v.easing[2]}, y2: ${v.easing[3]})`,
    ),
    `    }`,
    ``,
    `    public enum Layout {`,
    `        public enum SizeClass: String, CaseIterable, Sendable {`,
    ...classes.map(([k]) => `            case ${k}`),
    ``,
    `            public var minWidth: Double {`,
    `                switch self {`,
    ...classes.map(([k, v]) => `                case .${k}: return ${v.min}`),
    `                }`,
    `            }`,
    ``,
    `            public static func forWidth(_ width: Double) -> SizeClass {`,
    `                allCases.last(where: { width >= $0.minWidth }) ?? .${classes[0][0]}`,
    `            }`,
    `        }`,
    ``,
    `        public enum Pane {`,
    ...Object.entries(layout.panes).flatMap(([k, v]) => [
      `            public static let ${camel(k)}Default: Double = ${v.default}`,
      `            public static let ${camel(k)}Min: Double = ${v.min}`,
      `            public static let ${camel(k)}Max: Double = ${v.max}`,
    ]),
    `        }`,
    ``,
    `        /// Smallest desktop window (macOS). iOS and iPadOS windows are sized by the system.`,
    `        public enum Window {`,
    `            public static let minWidth: Double = ${layout.window.minWidth}`,
    `            public static let minHeight: Double = ${layout.window.minHeight}`,
    `        }`,
    ``,
    `        public enum Editor {`,
    `            public static let measure: Double = ${layout.editor.measure}`,
    `            public static func paddingX(_ sizeClass: SizeClass) -> Double {`,
    `                switch sizeClass {`,
    ...Object.entries(layout.editor.paddingX).map(([k, v]) => `                case .${k}: return ${v}`),
    `                }`,
    `            }`,
    `        }`,
    `    }`,
    `}`,
    ``,
  ].join("\n");
}

function buildKtTokens({ tokens }) {
  const { color, typography, spacing, sizing, effects, layout } = tokens;
  const classes = Object.entries(layout.sizeClasses);
  return [
    `// ${HEADER}`,
    `package io.github.colosan.ithaca.design.generated`,
    ``,
    `/** A light/dark color pair. Values are 0xAARRGGBB (pass straight to Compose Color(Long)). */`,
    `data class ColorPair(val light: Long, val dark: Long)`,
    ``,
    `data class TextStyleToken(val family: String, val size: Float, val lineHeight: Float, val tracking: Float, val weight: Int)`,
    ``,
    `data class ShadowToken(val y: Float, val blur: Float, val opacity: Float)`,
    ``,
    `/** duration is in milliseconds. */`,
    `data class MotionToken(val duration: Int, val x1: Float, val y1: Float, val x2: Float, val y2: Float)`,
    ``,
    `object Tokens {`,
    `    object Color {`,
    ...Object.entries(color.tokens).map(
      ([k, v]) => `        val ${camel(k)} = ColorPair(light = ${kotlinARGB(v.light)}, dark = ${kotlinARGB(v.dark)})`,
    ),
    `    }`,
    ``,
    `    object Typography {`,
    `        object Family {`,
    ...Object.entries(typography.families).map(([k, f]) => `            const val ${camel(k)} = ${ktStr(f.name)}`),
    `        }`,
    ...Object.entries(typography.styles).map(
      ([k, s]) =>
        `        val ${camel(k)} = TextStyleToken(family = Family.${camel(s.family)}, size = ${ktFloat(s.size)}, lineHeight = ${ktFloat(s.lineHeight)}, tracking = ${ktFloat(s.tracking)}, weight = ${s.weight})`,
    ),
    `    }`,
    ``,
    `    object Space {`,
    ...Object.entries(spacing.scale).map(([k, v]) => `        const val ${scaleId(k)} = ${ktFloat(v)}`),
    `    }`,
    ``,
    `    object Size {`,
    ...Object.entries(sizing.sizes).map(([k, v]) => `        const val ${camel(k)} = ${ktFloat(v)}`),
    `    }`,
    ``,
    `    object Radius {`,
    ...Object.entries(effects.radius).map(([k, v]) => `        const val ${camel(k)} = ${ktFloat(v)}`),
    `    }`,
    ``,
    `    object Shadow {`,
    ...Object.entries(effects.shadow).map(
      ([k, v]) => `        val ${camel(k)} = ShadowToken(y = ${ktFloat(v.y)}, blur = ${ktFloat(v.blur)}, opacity = ${ktFloat(v.opacity)})`,
    ),
    `    }`,
    ``,
    `    object Opacity {`,
    ...Object.entries(effects.opacity).map(([k, v]) => `        const val ${camel(k)} = ${ktFloat(v)}`),
    `    }`,
    ``,
    `    object Motion {`,
    ...Object.entries(effects.motion).map(
      ([k, v]) =>
        `        val ${camel(k)} = MotionToken(duration = ${v.duration}, x1 = ${ktFloat(v.easing[0])}, y1 = ${ktFloat(v.easing[1])}, x2 = ${ktFloat(v.easing[2])}, y2 = ${ktFloat(v.easing[3])})`,
    ),
    `    }`,
    ``,
    `    object Layout {`,
    `        enum class SizeClass(val minWidth: Float) {`,
    ...classes.map(([k, v], i) => `            ${upperSnake(k)}(${ktFloat(v.min)})${i === classes.length - 1 ? ";" : ","}`),
    ``,
    `            companion object {`,
    `                fun forWidth(width: Float): SizeClass = entries.last { width >= it.minWidth }`,
    `            }`,
    `        }`,
    ``,
    `        object Pane {`,
    ...Object.entries(layout.panes).flatMap(([k, v]) => [
      `            const val ${camel(k)}Default = ${ktFloat(v.default)}`,
      `            const val ${camel(k)}Min = ${ktFloat(v.min)}`,
      `            const val ${camel(k)}Max = ${ktFloat(v.max)}`,
    ]),
    `        }`,
    ``,
    `        /** Smallest desktop window (Windows). Android windows are sized by the system. */`,
    `        object Window {`,
    `            const val minWidth = ${ktFloat(layout.window.minWidth)}`,
    `            const val minHeight = ${ktFloat(layout.window.minHeight)}`,
    `        }`,
    ``,
    `        object Editor {`,
    `            const val measure = ${ktFloat(layout.editor.measure)}`,
    `            fun paddingX(sizeClass: SizeClass): Float = when (sizeClass) {`,
    ...Object.entries(layout.editor.paddingX).map(([k, v]) => `                SizeClass.${upperSnake(k)} -> ${ktFloat(v)}`),
    `            }`,
    `        }`,
    `    }`,
    `}`,
    ``,
  ].join("\n");
}

// ── Bundle ─────────────────────────────────────────────────────────────

export function buildOutputs(design = loadDesign()) {
  assertSameKeys(design);
  return {
    [OUT.css]: buildCss(design),
    [OUT.ts]: buildTs(design),
    [OUT.stringsTs]: buildStringsTs(design),
    [OUT.swiftTokens]: buildSwiftTokens(design),
    [OUT.swiftStrings]: buildSwiftStrings(design),
    [OUT.ktTokens]: buildKtTokens(design),
    [OUT.ktStrings]: buildKtStrings(design),
  };
}
